<?php
// Complete database setup script
echo "<h1>Complete Database Setup</h1>";
echo "<h2>Status: </h2>";

// Step 1: Check MySQL connection
echo "<h3>1. Testing MySQL Connection</h3>";
$host = 'localhost';
$user = 'root';
$pass = '';

try {
    echo "Connecting to MySQL...<br>";
    $conn = new mysqli($host, $user, $pass);

    if ($conn->connect_error) {
        echo "<span style='color: red;'>❌ Connection failed: " . htmlspecialchars($conn->connect_error) . "</span><br>";
        echo "<strong>SOLUTION:</strong> Please start MySQL in XAMPP Control Panel<br>";
        echo "<ol>
                <li>Open XAMPP Control Panel</li>
                <li>Click 'Start' next to 'MySQL'</li>
                <li>Wait for status to show 'Running'</li>
                <li>Refresh this page</li>
              </ol>";
        exit;
    }

    echo "<span style='color: green;'>✅ MySQL connection successful</span><br>";
    $server_info = $conn->server_info;
    echo "MySQL Version: $server_info<br>";

    // Step 2: Create Database
    echo "<h3>2. Creating Database</h3>";
    $db = 'pj_photography';
    if ($conn->query("CREATE DATABASE IF NOT EXISTS $db")) {
        echo "<span style='color: green;'>✅ Database 'pj_photography' created/exists</span><br>";
    } else {
        echo "<span style='color: red;'>❌ Database creation failed: " . htmlspecialchars($conn->error) . "</span><br>";
        exit;
    }

    // Step 3: Select Database
    echo "<h3>3. Selecting Database</h3>";
    if ($conn->select_db($db)) {
        echo "<span style='color: green;'>✅ Database selected</span><br>";
    } else {
        echo "<span style='color: red;'>❌ Database selection failed: " . htmlspecialchars($conn->error) . "</span><br>";
        exit;
    }

    // Step 4: Create Table
    echo "<h3>4. Creating Contacts Table</h3>";
    $table_sql = "CREATE TABLE IF NOT EXISTS contacts (
        id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(50) NOT NULL,
        email VARCHAR(50) NOT NULL,
        message TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )";

    if ($conn->query($table_sql)) {
        echo "<span style='color: green;'>✅ Contacts table created/verified</span><br>";
    } else {
        echo "<span style='color: red;'>❌ Table creation failed: " . htmlspecialchars($conn->error) . "</span><br>";
        exit;
    }

    // Step 5: Test Insert
    echo "<h3>5. Testing Data Insertion</h3>";
    $name = "Setup Test";
    $email = "test@example.com";
    $message = "This is a test message created during setup.";

    $stmt = $conn->prepare("INSERT INTO contacts (name, email, message) VALUES (?, ?, ?)");
    $stmt->bind_param("sss", $name, $email, $message);

    if ($stmt->execute()) {
        echo "<span style='color: green;'>✅ Test data inserted successfully (ID: " . $conn->insert_id . ")</span><br>";
    } else {
        echo "<span style='color: red;'>❌ Test insert failed: " . htmlspecialchars($stmt->error) . "</span><br>";
        exit;
    }

    $stmt->close();

    // Step 6: Update Config
    echo "<h3>6. Updating Configuration</h3>";
    $config_content = "<?php
// Database configuration - Auto-generated by setup script
define('DB_HOST', '$host');
define('DB_USER', '$user');
define('DB_PASS', '$pass');
define('DB_NAME', '$db');

// Create connection
function getDBConnection() {
    static \$conn = null;

    if (\$conn === null) {
        \$conn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);

        if (\$conn->connect_error) {
            error_log('Database connection failed: ' . \$conn->connect_error);
            die('Sorry, we are experiencing technical difficulties. Please try again later.');
        }

        \$conn->set_charset('utf8mb4');
    }

    return \$conn;
}
?>";

    if (file_put_contents('db_config.php', $config_content)) {
        echo "<span style='color: green;'>✅ Configuration file updated</span><br>";
    } else {
        echo "<span style='color: red;'>❌ Could not update configuration file</span><br>";
    }

    $conn->close();

    // Success message
    echo "<div style='background: #d4edda; color: #155724; padding: 15px; margin: 20px 0; border-radius: 5px; border: 1px solid #c3e6cb;'>
        <h2 style='margin-top: 0;'>🎉 Setup Complete!</h2>
        <p>Your contact form database is now ready. Contact form submissions will be saved to the database.</p>
    </div>";

    echo "<p style='font-size: 18px;'><a href='contact.php' style='color: #007bff; text-decoration: none; font-weight: bold;'>→ Test Your Contact Form Now</a></p>";

    echo "<h3>Quick Status Check:</h3>";
    echo "<ul>";
    echo "<li>MySQL connection: ✅ Working</li>";
    echo "<li>Database 'pj_photography': ✅ Created</li>";
    echo "<li>Contacts table: ✅ Ready</li>";
    echo "<li>Configuration: ✅ Updated</li>";
    echo "</ul>";

} catch (Exception $e) {
    echo "<span style='color: red;'>❌ Setup error: " . htmlspecialchars($e->getMessage()) . "</span><br>";
    echo "<p><strong>Need help?</strong> Make sure MySQL is running in XAMPP Control Panel.</p>";
}

echo "<hr><p><small>If you continue having issues, check the MySQL service in XAMPP Control Panel.</small></p>";
?>
